version: '3'
services:
  # Zookeeper and Kafka will go into own compose file
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - typeahead_network

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - typeahead_network
#-------------------------------
  trie_microservice:
    build: .
    ports:
      - "8080:8080"
    networks:
      - typeahead_network

networks:
  typeahead_network:
    external: true
